/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controller;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * JFrame class excension by the methods and variables needed 
 * to program be run
 * @author kamso
 */
public class SwingGUI extends javax.swing.JFrame {

    /**
     * Creates new form SwingGUI
     */
    public SwingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setMnemonic('B');
        jButton1.setText("jButton1");
        jButton1.setToolTipText("get prime numbers under N");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.setToolTipText("enter number N");

        jTree1.setToolTipText("here is the tree");
        jScrollPane1.setViewportView(jTree1);
        jTree1.getAccessibleContext().setAccessibleDescription("here prime numbers will be displayed");

        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("here exceptions are displayed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * function that run controller function with input from user
     * in jTextField1 when the button is clicked
     * @param evt is not used in this function
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Controller controller = new Controller(this);
        String[] textArray = {jTextField1.getText()};
        controller.controller(textArray);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * function sets passed text in jLabel1
     * @param text is set in jLabel1
     */
    public void setJLabel1(String text)
    {
        jLabel1.setText(text);
    }
    
    /**
     * function set passed text in jTextField1
     * @param text is set in jTextField1
     */
    public void setJTextField(String text) 
    {
        jTextField1.setText(""); // Clear any existing content
        jTextField1.setText(text); // Set the new text
    }
    
    /*
     * function prepares Tree to be clear and ready to fill later in program
    */
    public void setUpTree()
    {
        DefaultMutableTreeNode primeNumbersRoot = new DefaultMutableTreeNode("PrimeNumbers");
        jTree1.setModel(new DefaultTreeModel(primeNumbersRoot));
    }
    
    /**
     * function displays all passed primeNumbers in the Tree
     * @param primeNumbers array with primeNumbers
     * @param n number N passed by the user till wchich we detect primeNumbers
     */
    public void displayResultInATree(int[] primeNumbers, int n)
    {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Prime Numbers up to " + n);
        
        for (int i = 0; i <= primeNumbers.length-1; i++) 
            root.add(new DefaultMutableTreeNode(primeNumbers[i]));
        
        jTree1.setModel(new DefaultTreeModel(root));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
